name: Test core library
on:
  push:
    branches-ignore:
      - "gh-pages"

jobs:
  ctest-debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0

      - name: Install OpenCL
        run: |
          sudo apt-get update
          sudo apt-get install ocl-icd-opencl-dev

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Configure and build
        uses: threeal/cmake-action@v2.0.0
        with:
          generator: Ninja
          run-build: true
          options: |
            OTTO_BUILD_TESTS=ON
            OTTO_BUILD_EXAMPLES=OFF
            CMAKE_BUILD_TYPE=Debug

      - name: Run tests
        uses: threeal/ctest-action@v1.1.0
        with:
          build-config: Debug
          verbose: true

  ctest-release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0

      - name: Install OpenCL
        run: |
          sudo apt-get update
          sudo apt-get install ocl-icd-opencl-dev

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Configure and build
        uses: threeal/cmake-action@v2.0.0
        with:
          generator: Ninja
          run-build: true
          options: |
            OTTO_BUILD_TESTS=ON
            OTTO_BUILD_EXAMPLES=OFF
            CMAKE_BUILD_TYPE=Release

      - name: Run tests
        uses: threeal/ctest-action@v1.1.0
        with:
          build-config: Release
          verbose: true
